### ISSUE TITLE
Long Delay

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/sttm-desktop#124] opened 2018-05-09 10:23 UTC
I'm experiencing great delay when selecting a new gurbani line to display since the update to version 3.3.1.
The delay reminds me to the times when sttm worked with powerpoint. Really makes it hard to use while keertan.

I'm running windows 7.

Please boost the performance back to level it used to be on previous version if possible ji.

**Comment by tarunsingh5** [comment] 2018-07-04 22:09
duplicate of #113

**Closed by tarunsingh5** 2018-07-04 22:09 UTC
