### ISSUE TITLE
Toggle display screen on and off

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#155] opened 2018-05-31 16:38 UTC
I should be able to "end shabad" or have an easy one-click way to toggle the presentation window on and off to reveal the desktop background. At the moment users are closing the entire application between shabads to hide the window.

**Comment by inderpreetsingh** [comment] 2018-07-08 13:18
I am thinking we should not add any new option in display options as of current UI - may be fix that in 5.0 with new UI overhaul?

Thank you!

**Comment by maneetpaul** [comment] 2018-09-29 20:01
Duplicate of #245

**Closed by maneetpaul** 2018-09-29 20:01 UTC
Labels: enhancement
