### ISSUE TITLE
History switch should not auto-show slide

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#151] opened 2018-05-29 22:40 UTC
When you switch between different shabads in history, the app automatically displays whatever the tukk is highlighted in the history. I should be able to switch between the history without it auto changing what's seen on screen. I should be able to switch the current shabad and only have a tukk displayed from that shabad when I click on it in the current shabad pane.

**Comment by maneetpaul** [comment] 2018-09-03 20:42
@saintsoldierx I'm not sure if I agree with this. I personally feel that being to quickly switch from shabad to shabad via the history list is a benefit (especially when people keep going back to one specific tuk, needing to click on it twice would be an annoyance). Maybe we can add this as an option in the preferences for people to disable if they wish?

**Comment by maneetpaul** [comment] 2018-09-29 21:04
Duplicate of #232

**Closed by maneetpaul** 2018-09-29 21:04 UTC
Labels: bug
