### ISSUE TITLE
Add translit to search results for English searching

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1608] opened 2022-07-10 06:54 UTC
i think if searching by first letter anywhere in english, it should also show transliteration. Could we change the Gurbani to English (ONLY for this mode) and put Gurbani on 2nd line and writer/raag on a third line in the search results?

[ANG] [ENGLISH TRANSLITERATION]
[GURBANI]
[WRITER], [RAAG]

Reason is if someone is searching in English, they most likely are not able to read Gurmukhi fluently so may prefer to search and display Shabads in English instead.

**Comment by theamanjs** [comment] 2023-05-31 05:54
Duplicate of #1723 Closing this one

**Closed by theamanjs** 2023-05-31 05:54 UTC
