### ISSUE TITLE
9.0 Single Diplay Mode Issue

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1367] opened 2021-10-18 14:26 UTC
Some important issues encountered in Single Display Mode
{ *Priority: High, Blocking operations* }

1. No navigation occurring (Slides are not changeable) outside the Shabad tab.
2. Every new thing,
    - Bani from Sundar gutka
    - Hukamnama
    - Random Shabad
    - Shabads from History tab
    appears on the screen on switching to the Shabad tab.

Refer to the following video.
( Pauses in the video represent the use of navigation buttons that are not working )

https://user-images.githubusercontent.com/51584037/137750212-1f752986-f245-4c63-9eb4-54fb7968c35e.mp4

**Comment by inderpreetsingh** [comment] 2021-11-23 05:14
Issue is fixed and code is merged. Closing the issue.

**Comment by MySmilingTurban** [comment] 2022-01-03 18:05
Issue persists in the latest 9.0 build

**Comment by MySmilingTurban** [comment] 2022-01-03 18:08
![image](https://user-images.githubusercontent.com/51584037/147964324-9d068ac4-f97d-4a81-a521-1ac4ee891e4d.png)

Also, when navigating down the verses list, the layout behaves unexpectedly
Steps to reproduce:
- search jemnD
- go to verses tab and scroll down
- everything goes insane

**Comment by MySmilingTurban** [comment] 2022-01-04 13:00
@inderpreetsingh @Gauravjeetsingh , please reopen this issue as it persists in the latest build.

**Comment by Gauravjeetsingh** [comment] 2022-01-26 01:52
@MySmilingTurban just checked, I was unable to reproduce it.

It switches to shabad pane automaticallly now when we select a shabad from search.
Also, tried searched and scrolling down, couldn't find any issue.

Sometimes due to a lag in internet, virtual Mac doesn't fully update the screen with changes. Maybe its that?

Even in the following gif, you would see a longer delay between clicking on random shabad and the pane switch. That's because virtual Mac runs slow for me.
![single-display](https://user-images.githubusercontent.com/1990932/151089788-30bbc88e-4181-40b8-acf9-bcb3deedc3f1.gif)

**Comment by MySmilingTurban** [comment] 2022-01-26 16:04
@Gauravjeetsingh veerji,
Thanks for the commendable fix

I came through these few errors:
- Autoscroll works in Single Display mode, but as you can see in the attached screenshot, it is not correctly aligned.
- Also, now the final concern in Single Display Mode is when the side pane is minimised, neither navigation nor shortcuts work.

![image](https://user-images.githubusercontent.com/51584037/151199358-066004db-6080-4738-bf84-cbcfd4107b8d.png)

**Closed** 2022-02-22 13:13 UTC
Labels: fixed in branch
