### ISSUE TITLE
9.1.1 - Shabad presentation view not visible (MacOS)

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1742] opened 2023-03-24 02:24 UTC
Steps to reproduce:
1. Open app and search open any shabad
2. It doesn't display in presentation tab (sometimes happens on first app open and sometimes on second time app open)

<img width="1728" alt="Screenshot 2023-03-24 at 2 51 58 am" src="https://user-images.githubusercontent.com/51584037/227408392-ec0a6ed5-c759-4f04-b64f-d10116df0e7e.png">

**Comment by Gauravjeetsingh** [comment] 2023-03-24 06:47
@theamanjs can you please take a look into this, I wasn't able to reproduce it in windows.

**Comment by theamanjs** [comment] 2023-04-04 09:52
I was unable to reproduce this issue as well. Let's keep this issue open and remove it from 9.1.1 milestone for now.

**Comment by Gauravjeetsingh** [comment] 2023-07-19 02:38
Duplicate of #1806

**Closed by Gauravjeetsingh** 2023-07-19 02:38 UTC
