### ISSUE TITLE
When you go to prev/next shabad through shabad pane, that shabad is not stored in history.

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#1151] opened 2020-06-24 08:44 UTC
I am not sure if we wanted that as a behaviour, but pointing out (just in case). When we change the Shabad from next previous icons in shabad pane, that history is not saved in history pane.

**Comment by Gauravjeetsingh** [comment] 2023-07-19 04:37
Duplicate of https://github.com/KhalisFoundation/sttm-desktop/issues/1759

Closing this one.

**Closed by Gauravjeetsingh** 2023-07-19 04:37 UTC
Labels: bug
