### ISSUE TITLE
Would it be possible to update OBS when the Vaahiguroo slide or other non-Panktee slides are selected?

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1626] opened 2022-07-25 11:31 UTC
(Auto generated from slack)
Would it be possible to update OBS when the Vaahiguroo slide or other non-Panktee slides are selected?
https://khalis.slack.com/archives/CFS6E54PN/p1658115691739659

**Comment by Gauravjeetsingh** [comment] 2022-07-27 10:17
Duplicate of #1615 closing this out

**Closed by Gauravjeetsingh** 2022-07-27 10:17 UTC
