### ISSUE TITLE
Alpha should use stg api 

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#1138] opened 2020-06-18 15:48 UTC

**Comment by tsingh777** [comment] 2020-07-09 14:59
http://dev.sikhitothemax.org/ should start using staging api (https://stgapi.sikhitothemax.org/) as well so sync can work on alpha.

**Comment by prebhdevsingh** [comment] 2021-03-16 05:21
seems like a duplicate of https://github.com/KhalisFoundation/sttm-desktop/issues/1068

**Closed by prebhdevsingh** 2021-03-16 05:21 UTC
Labels: Tech debt
