### ISSUE TITLE
Create srt files whilst presenting

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#154] opened 2018-05-31 07:48 UTC
A feature when I press "record", i can have single text file that outputs timecodes and lines so I can add them easily to videos. This would be great to give users option of closed captioning (CC) or subtitles like on YouTube and other video platforms. This way, subtitles are optional rather than having them superimposed on the actual videos.

**Comment by maneetpaul** [comment] 2018-09-29 20:56
Duplicate of #317

**Closed by maneetpaul** 2018-09-29 20:56 UTC
Labels: enhancement
