### ISSUE TITLE
Bani Controller having issues with Sundar Gutka and Ceremonies

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#1312] opened 2021-02-25 15:42 UTC
Works fine with Shabads

**Comment by Gauravjeetsingh** [comment] 2021-03-02 07:30
Tried both ways, changing pankti on desktop and seeing on web and changing pankti on web and seeing on desktop. Highlight works fine in both.
![Peek 2021-03-02 12-58](https://user-images.githubusercontent.com/1990932/109613487-3a92c300-7b57-11eb-810f-732955e1902c.gif)

**Comment by saintsoldierx** [comment] 2021-03-02 07:37
I was also unable to reproduce the issue (STTM Beta - latest, MacOS, Safari on iOS). Works fine for me.

**Comment by Gauravjeetsingh** [comment] 2021-03-02 07:42
Closing this out then.

**Closed by Gauravjeetsingh** 2021-03-02 07:42 UTC
Labels: bug
