### ISSUE TITLE
Be able to choose text file output location

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#152] opened 2018-05-30 03:47 UTC
I want to have an easy way to be able to select where the txt file output should be saved to. This functionality should be disabled as default. Default location should be the users' desktop.

**Comment by lbk003** [comment] 2018-05-30 03:50
@saintsoldierx How does it get enabled?

**Comment by saintsoldierx** [comment] 2018-05-30 03:56
In options there is a slider button which says "output text file" or something similar which enables it. If enabled, a new option should appear underneath to be able to select a file location.

**Comment by saintsoldierx** [comment] 2018-05-30 03:58
![image](https://user-images.githubusercontent.com/27791330/40698257-0339d5c2-6383-11e8-8de5-8d366e43ca8d.png)
This is the option as it is currently in dev

**Comment by maneetpaul** [comment] 2018-09-29 20:58
Duplicate of #184

**Closed by maneetpaul** 2018-09-29 20:58 UTC
Labels: enhancement
