### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#1317] opened 2021-03-02 07:17 UTC
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/3928">3928</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div>From: Arshdeep Singh &lt;sarshdeep825@gmail.com&gt;<br>Subject: Suggestions about SikhiToTheMax<br>IP: 157.36.187.165 <br><br>Message Body:<br>Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh Ji!<br>Your app (SikhiToTheMax) is great! I started using this in 2020. I would like to give you a suggestion about the app (PC) for the presentations/overlay, that when we change a specific line in a shabad, it changes with no animation. It would be great if you add fade animation while changing line in shabad. I shall be thankful to you!<br>Arshdeep Singh<br>Waheguru Ji Ka Khalsa, Waheguru Ji Ki Fateh!<br><br>--<br>This e-mail was sent using the contact form on Khalis Foundation (<a href="http://khalisfoundation.org" rel="noreferrer">http://khalisfoundation.org</a>)<br><br>
</div>

**Comment by ManjotS** [comment] 2021-03-02 07:17
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/3928">3928</a> for this issue.</div>

**Comment by Gauravjeetsingh** [comment] 2023-11-22 10:33
Duplicate of #258 closing this out

**Closed by Gauravjeetsingh** 2023-11-22 10:33 UTC
Labels: fixed in branch, good first issue :baby:, acknowledged
