### ISSUE TITLE
autoplay toggle does nothing with no error

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#259] opened 2018-08-14 21:54 UTC
1. search for a shabad
2. open the shabad
3. go to settings
4. click autoplay
5. toggle just flashes

**Comment by tarunsingh5** [comment] 2018-08-14 21:55
can you please provide a video?

**Comment by ManjotS** [comment] 2018-08-14 22:02
![autoplay](https://user-images.githubusercontent.com/644885/44120973-fd6615e8-9fd2-11e8-8cd1-b560ffa1c254.gif)

**Comment by tsingh777** [comment] 2018-08-15 01:43
since it only makes since with Akhand Paatth View, I think we need to disable it unless APV is on.

**Comment by ManjotS** [comment] 2018-08-15 03:11
Why can't we auto cycle slides.

**Comment by lbk003** [comment] 2018-08-28 02:50
@maneetpaul  What is the expected behavior for the autoplay function? Please clarify.

**Comment by inderpreetsingh** [comment] 2018-12-10 07:54
I can't reproduce it 🤔

**Comment by inderpreetsingh** [comment] 2019-02-21 06:44
I am able to reproduce it in build. 🙏

**Comment by prebhdevsingh** [comment] 2021-03-15 18:57
I can see this potentially causing issues with auto-advancing slides during kirtan if someone switches back from the AP mode. I'd rather just hide the setting or provide an indication that this option only works w/ AP mode.

**Comment by Gauravjeetsingh** [comment] 2023-07-19 03:42
working in latest release, closing this out.

**Closed by Gauravjeetsingh** 2023-07-19 03:42 UTC
Labels: bug, good first issue :baby:
