### ISSUE TITLE
Back and forward buttons for shabad menu

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#72] opened 2018-02-12 10:57 UTC
https://files.slack.com/files-pri/T03QFACU3-F951JETQB/screen_shot_2018-02-06_at_11.50.45_pm.png

**Comment by ManjotS** [comment] 2018-02-12 16:32
This is a duplicate of #11

**Closed by ManjotS** 2018-02-12 16:32 UTC
