### ISSUE TITLE
Hukumnama

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/sttm-desktop#194] opened 2018-07-07 07:51 UTC
We should add hukumnama display option.
Full hukumnama/shabad on single screeen.
(Like old sttm was having split shabad)
First full shabad then full arth

**Comment by ManjotS** [comment] 2018-07-07 19:20
Closing as duplicate of #130

**Closed by ManjotS** 2018-07-07 19:20 UTC
